[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-ma-player"
dynamic = ["version"]
description = "OpenVoiceOS OCP player provider for Music Assistant"
requires-python = ">=3.12"
dependencies = [
    "music-assistant-plugin-manager",
    "ovos-bus-client>=2.9.1a1",
    "ovos-utils>=0.8.5",
    "ovos-pydantic-models>=0.3.0a1",
]

[project.entry-points."music_assistant.provider"]
ovos_player = "ovos_ma_player"

[tool.setuptools.dynamic]
version = { attr = "ovos_ma_player.version.__version__" }

[tool.setuptools.packages.find]
include = ["ovos_ma_player*"]

[tool.setuptools.package-data]
ovos_ma_player = ["manifest.json"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "strict"

[project.optional-dependencies]
test = ["pytest", "pytest-asyncio", "ovos-pydantic-models"]
